Basic CRUD for Requests
syouon/office-helper pull request #1
Opened 2017-02-12 17:15 UTC by 3ck0o

I didn't test it too much, but this should be all right as a quick CRUD for requests.
Please note that there are some issues with the REST controllers: We don't return a `ResponseEntity` every time (especially for **delete** operations) -> Errors can be difficult to handle in the front-end. 

Oh, and... There are no tests :trollface: 
...
...
Yet !

2017-02-12 20:56 UTC, Ezwal commented
I don't understand why there is no test. I mean it's pretty important!
So for the love of god write those test

2017-02-12 20:57 UTC, vouill commented
I am really confused too

2017-02-13 10:46 UTC, syouon requested changes

2017-02-13 10:46 UTC, syouon commented on domain/src/main/java/com/officehelper/domain/Request.java
> +import java.util.Date;
On va plutôt utiliser les LocalDate (ou LocalDateTime selon le cas) de Java 8. L'api java.util.Date est plutôt dépréciée

2017-02-13 10:46 UTC, syouon commented on domain/src/main/java/com/officehelper/domain/Request.java
> + * Created by 3ck0o on 2/12/2017.
On va essayer de ne pas mettre d'en-tête pour respecter le "no code ownership"

2017-02-13 10:46 UTC, syouon commented on domain/src/main/java/com/officehelper/domain/Request.java
> +    public Long getUserId() {
Je pense pas que ce soit utile ça, et ça respecte pas le model objet de Java

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/RequestRepository.java
> +    List<Request> findByStatus(RequestStatus userId);
RequestStatus userId ? Ce serait pas plutôt RequestStatus requestStatus ?

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/converter/RequestStatusConverter.java
> +public class RequestStatusConverter extends EnumConverter<String, RequestStatus> {
Stylé :+1:

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +    @Inject
C'est une mauvaise habitude de faire des injections par champs, il faut faire des injections par constructeurs

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +    public Optional<Request> delete(long id) {
Ici tu vas chercher une Request avec findOne puis tu crées un nouveau Record si tu l'as trouvé: ça demande de faire une requête en plus et de créer un nouveau record. Il vaut mieux que tu fasses un fetchOptional pour récupérer le record en base (s'il existe) et le supprimer, ça évite de créer un record en trop. Tu as un exemple dans la méthode delete du UserRepository.

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +        return requestRecordMapper.map(requestRecord);
C'est vrai que c'est mieux dans cet ordre :)

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +        return create.executeUpdate(requestRecord) > 0;
Stylé :+1:

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +    public void setCreate(DSLContext create) {
Pas besoin des deux setters, ils seront injectés par constructeur.

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/UserRepositoryImpl.java
> +        return mapper.map(userRecord);
Stylé :+1:

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/UserRepositoryImpl.java
> +        return Optional.empty();
Stylé :+1:

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/mapper/RequestRecordMapper.java
> +    @Inject
Pareil ici, injection par constructeur

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/mapper/RequestRecordMapper.java
> +        request.setUser(userRepository.get(requestRecord.getUserId().longValue()));
Utilise le findOne ici, on a deux méthodes qui font sensiblement la même chose, il faut l'enlever même si ça oblige à faire un test sur l'optional ici (et renvoyer une exception si le user n'est pas présent)

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/UserRepositoryImpl.java
> +    public User get(long id) {
Pareil, pas besoin de cette méthode

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/UserRepository.java
> +    User get(long id);
Pas besoin de cette méthode ici, on a le findOne (cf. commentaire plus bas)

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/mapper/RequestRecordMapper.java
> +    public void setRequestStatusConverter(RequestStatusConverter requestStatusConverter) {
Pareil ici, pas besoin des setters

2017-02-13 10:46 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/mapper/UserRecordMapper.java
> +public class UserRecordMapper implements RecordMapper<UserRecord, User> {
Stylé :+1:

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/command/AddRequestCommand.java
> +    private Long userId;
Ici on va laisser le userId pour le moment, mais on l'enlèvera ensuite (en récupérant le user par token de session)

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/command/AddRequestCommand.java
> +    @NotBlank
Ici je pense qu'il faudrait rajouter une validation sur la longueur max acceptée du title

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/command/AddRequestCommand.java
> +    @NotBlank
Cette annotation ne fonctionne que sur les String. Il faut que tu utilise @NotNull ici.

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/command/AddRequestCommand.java
> +    @NotBlank
Pareil ici, il faut plutôt utiliser @NotNull et rajouter @Min(0 ou 1). Après faut voir si on oblige à mettre une quantité ou pas

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +    @Inject
Pareil, injection par constructeur

2017-02-13 10:46 UTC, syouon commented on domain/src/main/java/com/officehelper/domain/Request.java
> +    private Date creationDate;
Pareil ici, on peut directement initialiser à now()

2017-02-13 10:46 UTC, syouon commented on domain/src/main/java/com/officehelper/domain/Request.java
> +    private RequestStatus status;
Ici ce serait cool d'initialiser status à RequestStatus.NEW, ça évite de le setter à chaque fois qu'on crée une Request.

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +        request.setStatus(RequestStatus.NEW);
Ici, plus besoin du coup vu qu'on initialise lors de la création d'une request

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +        request.setCreationDate(new Date());
Pareil ici

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +        return requestRepository.save(request);
Tu pourrais rajouter un log d'info pour qu'on puisse suivre les opérations pls ?

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +    @Transactional
Ici la transaction est read only, tu peux rajouter le paramètre readOnly = true.

2017-02-13 10:46 UTC, syouon commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +    @Transactional
Pareil ici

2017-02-13 10:46 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
> +    @Inject
Pareil ici

2017-02-13 10:46 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
> +    public ResponseEntity<Request> save(@RequestBody AddRequestCommand command, BindingResult bindingResult) {
Ici il faut ajouté l'annotation @Valid sur la commande pour que la validation soit prise en compte.

2017-02-13 10:46 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
> +        return new ResponseEntity<Request>(requestService.save(command), HttpStatus.CREATED);
Pas besoin de spécifier `<Request>` ici, Java va inférer le type.

2017-02-13 10:46 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
> +    public ResponseEntity<Request> update(@RequestBody UpdateRequestCommand command, BindingResult bindingResult) {
Pareil @Valid. Et on renvoie qu'une ResponseEnity (pas `ResponseEntity<Request>`) car l'update ne renvoie pas l'objet Request

2017-02-13 10:46 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
> +        return new ResponseEntity<Request>(requestService.update(command), HttpStatus.NO_CONTENT);
Pareil, pas de `<Request>` et du coup il faut faire l'update à l'extérieur de la ResponseEntity

2017-02-13 10:46 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
> +    public void setRequestService(RequestService requestService) {
Pas besoin du setter ici aussi

2017-02-13 10:46 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
> +    private String handleDuplicateEntityException(DuplicateEntityException e) {
Pas besoin de cette méthode, le RequestService ne renvoie jamais de DuplicateKeyException

2017-02-13 14:43 UTC, 3ck0o commented on domain/src/main/java/com/officehelper/domain/Request.java
> +    public Long getUserId() {
J'en ai besoin pour JOOQ, il cherche la clé étrangère pour le userId et il lui faut un getter :)

2017-02-13 14:44 UTC, 3ck0o commented on service/src/main/java/com/officehelper/service/command/AddRequestCommand.java
> +    private Long userId;
Yep 👍

2017-02-13 15:02 UTC, 3ck0o commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +    @Inject
Ouais mais ça fait des constructeurs dégueux :/
Mais ok, je vais refactor.

2017-02-13 22:12 UTC, 3ck0o commented on repository/src/main/java/com/officehelper/repository/mapper/RequestRecordMapper.java
> +        request.setUser(userRepository.get(requestRecord.getUserId().longValue()));
En fait non, c'est useless ce que j'ai fait, ça fait faire deux appels pour remonter une entité. C'est pas worth. J'ai tout refactor pour faire la jointure directement :)

2017-02-13 22:21 UTC, 3ck0o commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +    public Optional<Request> delete(long id) {
En fait, je fait tout d'un coup en une requête maintenant. Après mûre réflexion, je vois pas l'intérêt de renvoyer ce qu'on vient de delete à la vue, je renvoie juste un boolean du coup, et je fais comme pour l'update.

2017-02-14 09:17 UTC, 3ck0o commented
Ne merge pas pour l'instant j'ai juste push un WIP, y'a quelques soucis encore :x

2017-02-14 09:40 UTC, syouon requested changes

2017-02-14 09:40 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/mapper/RequestRecordMapper.java
> +    public Request map(Record record) {
Ca marche plus avec un RequestRecord ? :(

2017-02-14 09:40 UTC, syouon commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +        logger.info("Added new request [%s]", newRequest.getId());
Les placeholders en SLF4J se font avec cette syntaxe '{}'. Les '%s/%d' s'utilisent dans les String.format()

2017-02-14 09:40 UTC, syouon commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
>      private String handleDataNotFoundException(DataNotFoundException e) {
Rebase toi sur master, maintenant on renvoie un dto ErrorResponse pour ce genre de cas :)

2017-02-14 09:40 UTC, syouon commented on domain/src/main/java/com/officehelper/domain/Request.java
>      private Integer quantity;
Vu qu'on rend obligatoire le quantity, tu peux le passer en int ici aussi

2017-02-14 09:40 UTC, syouon commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +                .join(USER).on(USER.ID.equal(REQUEST.USER_ID))
Great ! :+1:

2017-02-14 10:44 UTC, 3ck0o commented on web/src/main/java/com/officehelper/controller/RequestRestController.java
>      private String handleDataNotFoundException(DataNotFoundException e) {
Ah cool c'est plus propre !

2017-02-14 10:50 UTC, 3ck0o commented on repository/src/main/java/com/officehelper/repository/mapper/RequestRecordMapper.java
> +    public Request map(Record record) {
Nan à cause de la jointure. Mais comme ça aussi ça passe plus pour l'add et l'update faudra qu'on en discute.

2017-02-14 10:51 UTC, 3ck0o commented on service/src/main/java/com/officehelper/service/impl/RequestServiceImpl.java
> +        logger.info("Added new request [%s]", newRequest.getId());
Ah ! Ok je changerai ça.

2017-02-14 10:52 UTC, 3ck0o commented on repository/src/main/java/com/officehelper/repository/impl/RequestRepositoryImpl.java
> +                .join(USER).on(USER.ID.equal(REQUEST.USER_ID))
Pas si great que ça, ça crée d'autres problèmes, je t'expliquerai :/

2017-02-23 16:16 UTC, syouon requested changes

2017-02-23 16:16 UTC, syouon commented on domain/src/main/java/com/officehelper/domain/Request.java
> +    private Date orderDate;
T'as oublié de passer en LocalDate ici aussi (et en dessous aussi)

2017-02-23 16:20 UTC, 3ck0o commented on domain/src/main/java/com/officehelper/domain/Request.java
> +    private Date orderDate;
Ah, fuck this shit. Je savais que j'avais oublié de faire un truc :x

2017-02-23 16:46 UTC, syouon approved these changes
Looks Good To Me :+1:

2017-02-23 16:46 UTC, merged