Externalize properties not to have them in pom
syouon/office-helper pull request #13
Opened 2017-04-20 21:13 UTC by romain-trotard

Déplace vite fais les properties (j'ai mis un password pour root par contre)

2017-04-20 21:16 UTC, romain-trotard commented
test this please

2017-04-21 09:51 UTC, syouon requested changes

2017-04-21 09:51 UTC, syouon commented on repository/pom.xml
> +                <version>1.0.0</version>
Tu peux mettre la version dans les properties maven ?

2017-04-21 09:51 UTC, syouon commented on repository/src/main/resources/database.properties
> +db.port=3306
mysql.port

2017-04-21 14:17 UTC, syouon approved these changes

2017-04-21 14:17 UTC, syouon commented on repository/pom.xml
> +                                <file>src/main/resources/database.properties</file>
Ce serait mieux de le déplacer vers le dossier config/database je pense

2017-04-21 15:24 UTC, syouon approved these changes

2017-04-21 15:26 UTC, merged