added docker container for mysql server
syouon/office-helper pull request #5
Opened 2017-02-20 13:03 UTC by benaich

first pr

2017-02-20 17:37 UTC, 3ck0o reviewed
@syouon je te laisse faire une autre passe :p

2017-02-20 17:39 UTC, 3ck0o commented on tools/docker/docker-compose.yml
> +    MYSQL_PORT: officehelper_db
J'y connais rien mais ça serais pas plutôt `MYSQL_PORT: 3306` ?

2017-02-20 19:41 UTC, benaich commented on tools/docker/docker-compose.yml
> +    MYSQL_PORT: officehelper_db
hahahahahahaha

2017-02-20 19:43 UTC, benaich commented on tools/docker/docker-compose.yml
> +    MYSQL_PORT: officehelper_db
bien vu, je dois même pas ajouté cette ligne

2017-02-21 10:54 UTC, syouon requested changes
Voilà pour mes retours ! Par contre il vaut mieux que tu déplaces tout ça dans le dossier config. Donc tout tes fichiers seraient dans le dossier config/docker/mysql.

- config
    - docker
        - mysql
            - Dockerfile
            - docker-compose.yml
            - schema.sql
            - run.sh

2017-02-21 10:54 UTC, syouon commented on README.md
> +    git clone git@github.com:mirakl/batch-admin.git
mirakl/batch-admin ? :p

2017-02-21 10:54 UTC, syouon commented on tools/docker/docker-compose.yml
> +  image: mysql
On va pas utiliser la section "image" ici, on va plutôt builder l'image avec notre propre Dockerfile (je l'ai déjà faite, je vais te l'envoyer). Donc il faudra remplacer cette ligne par une section "build: ."

2017-02-21 10:54 UTC, syouon commented on tools/docker/docker-compose.yml
> +    - ./data:/docker-entrypoint-initdb.d
Ici dans la section "volumes", il faut déclarer le conteneur docker qui va persister les données.

Donc la syntaxe est:
- {NOM_DU_CONTENEUR}:{DOSSIER_DE_PERSISTANCE}

Dans notre cas, NOM_DU_CONTENEUR serait "mysql-data" (par exemple) et DOSSIER_DE_PERSISTANCE serait "/var/lib/mysql".
Donc il faut juste que tu changes ça, parce que le dossier "docker-entrypoint-initdb.d" est utilisé pour lancer des scripts d'initialisation, pas pour stocker des données.

2017-02-21 10:54 UTC, syouon commented on README.md
> +
Tu devrais ajouter une section "Requirements" qui décrit les technos à installer (docker, docker-composer si on utilise docker...)

2017-02-21 10:54 UTC, syouon commented on tools/docker/docker-compose.yml
> +  environment:
Tu peux enlever toute la section "environment", tout sera setté dans le dockerfile.

2017-02-21 19:23 UTC, benaich commented on README.md
> +    git clone git@github.com:mirakl/batch-admin.git
lol

2017-02-21 19:27 UTC, benaich commented on tools/docker/docker-compose.yml
> +    - ./data:/docker-entrypoint-initdb.d
oui c'est ce que j'essaie de faire en fait, je veux exécuter un script au démarrage la création des tables et ses scripts se trouve dans le répertoire ./data je l'i peut être mal nomé

2017-02-21 19:48 UTC, benaich commented on tools/docker/docker-compose.yml
> +  image: mysql
je ne vois pas pourquoi on doit builder notre propre image, IMHO docker-compose est largement suffisant (on en parlera demain)

2017-02-21 19:52 UTC, benaich commented on README.md
> +
même si docker n'est pas vraiment required ? vu que je peut installer un serveur mysql sur ta machine sans avoir besoin d'installer docker

2017-02-22 08:38 UTC, syouon commented on README.md
> +
Tu peux faire une section avec les technos obligatoires (maven3, jdk8?) et dire ensuite qu'il faut soit mysql soit docker et docker-compose d'installer.

2017-02-22 08:42 UTC, syouon commented on tools/docker/docker-compose.yml
> +  image: mysql
Le truc c'est qu'on a déjà un script schema.sql qui initialise la bdd et crée le user 'developer'. Donc si tu utilises que l'image docker mysql, il faudra que tu spécifies (comme tu l'a fait) les informations de bdd et les user credentials. Du coup ça duplique les informations.

2017-02-22 08:57 UTC, benaich commented on README.md
> +
ok

2017-02-22 10:59 UTC, benaich commented on README.md
> +
more detail in a futur pr

2017-02-28 16:22 UTC, 3ck0o commented on README.md
> +    mvn spring-boot:run
Si on suit les steps du readme, ça ne se lance pas ! Quand je tape `mvn spring-boot:run` la console me crache un
`Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.1.RELEASE:run (default-cli) on project office-helper: Unable to find a suitable main class, please add a 'mainClass' property`
Je suppose que le plugin est pas configuré.

2017-02-28 16:39 UTC, syouon commented on README.md
> +    mvn spring-boot:run
@3ck0o Les steps ne sont pas bonnes, il faut se déplacer dans le module web avant de faire la commande `mvn spring-boot:run`. (Ce serait bien aussi de dire qu'avec son IDE préféré, il faut utiliser la classe OfficeHelperApplication)

2017-02-28 20:32 UTC, benaich commented on README.md
> +    mvn spring-boot:run
ok je vais tester ça

2018-01-16 13:46 UTC, closed without merging